---
branches:
  only:
    - master

language: go

go:
  - 1.12.x

os:
  - linux
  - osx
  - windows

dist: trusty

install: true

script:
  - cd $TRAVIS_BUILD_DIR
  - echo $PWD
  # build and test in the c-shared mode
  - make r2pm_c
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then export LD_LIBRARY_PATH=.; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then sudo cp libr2pm.so /usr/lib; fi
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then cp libr2pm.so .; fi
  # run
  - ./r2pm_c

  # build as a Go program
  - make r2pm
  - ./r2pm init
  - ./r2pm delete
  # - ./r2pm -s r2dec | grep -c Decompiler
